date: last-modified

filters:
  - include-code-files

format:
  html:
    toc: true

knitr:
  opts_chunk:
    eval: false
    comment: "#>"
    collapse: true
    message: true
    warning: false
    out.width: 100%
