---
title: "Vue d'ensemble"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vue d'ensemble}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(edstr)
```

## Test

```{r}
edstr_config(dest_dir = "S:/_FRACTURES_OSTEOPOROSE/test_urg",
             dest_filename = "test_urg",
             str = "S:/_R_/edstr_config/str.RData",
             concepts = "S:/_R_/edstr_config/concepts.RData",
             split = "S:/_R_/edstr_config/split/urg/urg_split.RData",
             text = "text")
```

Les arguments peuvent interpréter la syntaxe [glue](https://glue.tidyverse.org/).

```{r}
.r <- "S:/_R_/edstr_config"

edstr_config(dest_dir = "S:/_FRACTURES_OSTEOPOROSE/test_urg",
             dest_filename = "test_urg",
             str = "{.r}/str.RData",
             concepts = "{.r}/concepts.RData",
             split = "{.r}/split/urg/urg_split.RData",
             text = "text")
```

Seuls les arguments `dest_dir` et `dest_filename` sont indispensables.

```{r}
edstr_config(dest_dir = "S:/_FRACTURES_OSTEOPOROSE/test_urg",
             dest_filename = "test_urg")
```

Les éléments non créés seront listés en prenant la valeur `NULL`.

```{r}
.config
```



