#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom cli cli_alert_info
#' @importFrom cli cli_alert_success
#' @importFrom cli cli_alert_warning
#' @importFrom cli cli_end
#' @importFrom cli cli_h1
#' @importFrom cli cli_li
#' @importFrom cli cli_progress_done
#' @importFrom cli cli_progress_step
#' @importFrom cli cli_rule
#' @importFrom cli cli_text
#' @importFrom cli cli_ul
#' @importFrom cli col_blue
#' @importFrom config get
#' @importFrom dplyr across
#' @importFrom dplyr add_row
#' @importFrom dplyr all_of
#' @importFrom dplyr anti_join
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr collect
#' @importFrom dplyr count
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr expr
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr lst
#' @importFrom dplyr matches
#' @importFrom dplyr mutate
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pick
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr sql
#' @importFrom dplyr starts_with
#' @importFrom dplyr summarise
#' @importFrom dplyr tbl
#' @importFrom fs dir_create
#' @importFrom glue glue
#' @importFrom gt cell_text
#' @importFrom gt cells_body
#' @importFrom gt cells_column_labels
#' @importFrom gt gt
#' @importFrom gt gt_preview
#' @importFrom gt opt_css
#' @importFrom gt px
#' @importFrom gt sub_missing
#' @importFrom gt tab_options
#' @importFrom gt tab_style
#' @importFrom here here
#' @importFrom htmltools css
#' @importFrom htmltools save_html
#' @importFrom lifecycle deprecated
#' @importFrom openxlsx2 fmt_txt
#' @importFrom openxlsx2 wb_add_border
#' @importFrom openxlsx2 wb_add_cell_style
#' @importFrom openxlsx2 wb_add_data_table
#' @importFrom openxlsx2 wb_add_fill
#' @importFrom openxlsx2 wb_add_font
#' @importFrom openxlsx2 wb_add_worksheet
#' @importFrom openxlsx2 wb_color
#' @importFrom openxlsx2 wb_dims
#' @importFrom openxlsx2 wb_get_sheet_names
#' @importFrom openxlsx2 wb_open
#' @importFrom openxlsx2 wb_save
#' @importFrom openxlsx2 wb_set_col_widths
#' @importFrom openxlsx2 wb_to_df
#' @importFrom openxlsx2 wb_workbook
#' @importFrom purrr compact
#' @importFrom purrr imap
#' @importFrom purrr keep
#' @importFrom purrr list_c
#' @importFrom purrr list_flatten
#' @importFrom purrr list_modify
#' @importFrom purrr list_rbind
#' @importFrom purrr list_transpose
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map2
#' @importFrom purrr pluck
#' @importFrom purrr pluck_depth
#' @importFrom purrr reduce
#' @importFrom purrr reduce2
#' @importFrom reactable colDef
#' @importFrom reactable reactable
#' @importFrom reactable reactableTheme
#' @importFrom readr read_csv
#' @importFrom readr read_lines
#' @importFrom readr write_excel_csv
#' @importFrom RJDBC JDBC
#' @importFrom rlang :=
#' @importFrom rlang %||%
#' @importFrom rlang arg_match
#' @importFrom rlang check_dots_empty
#' @importFrom rlang enexpr
#' @importFrom rlang inject
#' @importFrom rlang is_named
#' @importFrom rlang list2
#' @importFrom rlang set_names
#' @importFrom rstudioapi askForPassword
#' @importFrom scales label_percent
#' @importFrom stats median
#' @importFrom stats quantile
#' @importFrom stringi stri_detect_regex
#' @importFrom stringr regex
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_ends
#' @importFrom stringr str_extract
#' @importFrom stringr str_extract_all
#' @importFrom stringr str_flatten
#' @importFrom stringr str_flatten_comma
#' @importFrom stringr str_glue
#' @importFrom stringr str_remove
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_squish
#' @importFrom stringr str_starts
#' @importFrom stringr str_subset
#' @importFrom stringr str_to_kebab
#' @importFrom stringr str_unique
#' @importFrom stringr str_view
#' @importFrom tibble as_tibble
#' @importFrom tibble enframe
#' @importFrom tibble rownames_to_column
#' @importFrom tibble tibble
#' @importFrom tictoc tic
#' @importFrom tictoc toc
#' @importFrom tidyr drop_na
#' @importFrom tidyr last_col
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr unnest
#' @importFrom tidytext unnest_tokens
#' @importFrom utils menu
#' @importFrom withr local_options
#' @importFrom withr local_seed
## usethis namespace: end
NULL
