on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: prek

permissions: read-all

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        with:
          extra-args: --all-files --skip prose-lint
